snd-003-objs := 003.o 003_pcm.o \
		003_midi.o 003_stream.o 003_lowlevel.o 

snd-firewire-lib-objs := lib.o iso-resources.o packets-buffer.o \
			 fcp.o cmp.o digimagic.o amdtp.o 

obj-m += snd-firewire-lib.o
obj-m += snd-003.o
